<b>Problem Statement 1: </b><br>Write a function so that the columns of the output matrix are powers of the input
vector.<br>The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br>HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [4]:
# importing numpy as np
import numpy as np 
  
array_input = np.array([1, 2, 3, 4, 5])    #create & assign array data type value to variable
  
print("The input vector is - ",array_input)#print input data

result = np.vander(array_input)            #vander function is used to calculate Vandermonde matrix
#By default(increasing=False)
print ("Decreasing matrix - \n",result)    #print decreasing matrix data

result = np.vander(array_input,increasing=True) 
  
print ("Increasing matrix - \n",result)    #print increasing matrix data

The input vector is -  [1 2 3 4 5]
Decreasing matrix - 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Increasing matrix - 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


<b>Problem Statement 2:</b><br>
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:<br>
The moving average sequence has n-k+1 elements as shown below.<br>
The moving averages with k=4 of a ten-value sequence (n=10) is shown below<br>
i 1 2 3 4 5 6 7 8 9 10<br>
===== == == == == == == == == == ==<br>
Input 10 20 30 40 50 60 70 80 90 100<br>
y1 25 = (10+20+30+40)/4<br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [8]:
import numpy as np

#declare and define function
def moving_average(arr_input, n) :
    asum = np.cumsum(arr_input, dtype=int)    #get cumulative sum of numbers
    asum[n:] = asum[n:] - asum[:-n]           #break array based on n & subtract to get result
    return asum[n - 1:] / n                   #divide by n to get average

#arr creation
arr_input = np.array([10,20,30,40,50,60,70,80,90,100])

#function call & store the result
result = np.array(moving_average(arr_input,4)).round(2)

#print values
print("Moving averages are -")
for i in result:
    print(i)
    
print("Total values in moving average sequence is ",(len(result)))

Moving averages are -
25.0
35.0
45.0
55.0
65.0
75.0
85.0
Total values in moving average sequence is  7


<b>Question</b><br>
Write a function to find moving average in an array over a window:<br>
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [9]:
#arr creation
arr_input_2 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

#function call & store the result
result2 = np.array(moving_average(arr_input_2,4)).round(2)

#print values
print("Moving averages are -")
for i in result2:
    print(i)
    
print("Total values in moving average sequence is ",(len(result2)))

Moving averages are -
4.25
5.5
6.75
7.75
23.5
39.5
57.25
79.25
88.0
107.5
Total values in moving average sequence is  10
